export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';

export const REGISTER_ATTEMPT = 'REGISTER_ATTEMPT';
export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL';

export const VALIDATION_ATTEMPT = 'VALIDATION_ATTEMPT';
export const VALIDATION_SUCCESS = 'VALIDATION_SUCCESS';

export const STORE_TOKEN = 'STORE_TOKEN';

export const LOGOUT = 'LOGOUT';
